Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml Update laravel.yml

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -12,24 +12,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
-      with:
-        php-version: '8.0'
-    - uses: actions/checkout@v2
-    - name: Copy .env
-      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
-    - name: Install Dependencies
-      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
-    - name: Generate key
-      run: php artisan key:generate
-    - name: Directory Permissions
-      run: chmod -R 777 storage bootstrap/cache
-    - name: Create Database
+    - uses: actions/checkout@v1
+
+    - name: Install dependencies
+      run: cp .env.example .env && docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/opt -w /opt laravelsail/php80-composer:latest composer install --ignore-platform-reqs
+
+    # In this step, this action saves a list of existing images,
+    # the cache is created without them in the post run.
+    # It also restores the cache if it exists.
+    - uses: satackey/action-docker-layer-caching@v0.0.11
+      # Ignore the failure of a step and avoid terminating the job.
+      continue-on-error: true
+
+    - name: Build environment
+      run: ./vendor/bin/sail build
+
+    - name: Start all the environment
+      run: source .env && export WWWUSER=$UID && export WWWGROUP=$GID && ./vendor/bin/sail up -d
+
+    - name: Wait for the environment to get up
       run: |
-        mkdir -p database
-        touch database/database.sqlite
-    - name: Execute tests (Unit and Feature tests) via PHPUnit
-      env:
-        DB_CONNECTION: sqlite
-        DB_DATABASE: database/database.sqlite
-      run: vendor/bin/phpunit
+        while ! docker-compose exec -T mysql mysqladmin --user=$DB_USERNAME --password=$DB_PASSWORD --host "127.0.0.1" ping --silent &> /dev/null ; do
+            echo "Waiting for database connection..."
+            sleep 2
+        done
+
+
+    - name: Run the tests
+      run: export WWWUSER=$UID && export WWWGROUP=$GID && docker-compose exec -T dogebank.local vendor/bin/phpunit
